import React from 'react';
export const lexerDetails = () => <div>lexer distinct</div>;
export const lexer_detail_0 = (p:any)=> <div>lexer 0 tokenize</div>;
export const lexer_detail_1 = (p:any)=> <div>lexer 1 keywords</div>;
export const lexer_detail_2 = (p:any)=> <div>lexer 2 contract terms</div>;
export const lexer_detail_3 = (p:any)=> <div>lexer 3 lex</div>;
export const lexer_detail_4 = (p:any)=> <div>lexer 4 tokenize</div>;
export const lexer_detail_5 = (p:any)=> <div>lexer 5 keywords</div>;
export const lexer_detail_6 = (p:any)=> <div>lexer 6 contract terms</div>;
export const lexer_detail_7 = (p:any)=> <div>lexer 7 lex</div>;
export const lexer_detail_8 = (p:any)=> <div>lexer 8 tokenize</div>;
export const lexer_detail_9 = (p:any)=> <div>lexer 9 keywords</div>;
export const lexer_detail_10 = (p:any)=> <div>lexer 10 contract terms</div>;
export const lexer_detail_11 = (p:any)=> <div>lexer 11 lex</div>;
export const lexer_detail_12 = (p:any)=> <div>lexer 12 tokenize</div>;
export const lexer_detail_13 = (p:any)=> <div>lexer 13 keywords</div>;
export const lexer_detail_14 = (p:any)=> <div>lexer 14 contract terms</div>;
export const lexer_detail_15 = (p:any)=> <div>lexer 15 lex</div>;
export const lexer_detail_16 = (p:any)=> <div>lexer 16 tokenize</div>;
export const lexer_detail_17 = (p:any)=> <div>lexer 17 keywords</div>;
export const lexer_detail_18 = (p:any)=> <div>lexer 18 contract terms</div>;
export const lexer_detail_19 = (p:any)=> <div>lexer 19 lex</div>;