import React from 'react';
export const formatterDetails = () => <div>formatter distinct</div>;
export const formatter_detail_0 = (p:any)=> <div>formatter 0 pretty print</div>;
export const formatter_detail_1 = (p:any)=> <div>formatter 1 style</div>;
export const formatter_detail_2 = (p:any)=> <div>formatter 2 indent</div>;
export const formatter_detail_3 = (p:any)=> <div>formatter 3 wrap</div>;
export const formatter_detail_4 = (p:any)=> <div>formatter 4 pretty print</div>;
export const formatter_detail_5 = (p:any)=> <div>formatter 5 style</div>;
export const formatter_detail_6 = (p:any)=> <div>formatter 6 indent</div>;
export const formatter_detail_7 = (p:any)=> <div>formatter 7 wrap</div>;
export const formatter_detail_8 = (p:any)=> <div>formatter 8 pretty print</div>;
export const formatter_detail_9 = (p:any)=> <div>formatter 9 style</div>;
export const formatter_detail_10 = (p:any)=> <div>formatter 10 indent</div>;
export const formatter_detail_11 = (p:any)=> <div>formatter 11 wrap</div>;
export const formatter_detail_12 = (p:any)=> <div>formatter 12 pretty print</div>;
export const formatter_detail_13 = (p:any)=> <div>formatter 13 style</div>;
export const formatter_detail_14 = (p:any)=> <div>formatter 14 indent</div>;
export const formatter_detail_15 = (p:any)=> <div>formatter 15 wrap</div>;
export const formatter_detail_16 = (p:any)=> <div>formatter 16 pretty print</div>;
export const formatter_detail_17 = (p:any)=> <div>formatter 17 style</div>;
export const formatter_detail_18 = (p:any)=> <div>formatter 18 indent</div>;
export const formatter_detail_19 = (p:any)=> <div>formatter 19 wrap</div>;