import React from 'react';
export const lspDetails = () => <div>lsp distinct</div>;
export const lsp_detail_0 = (p:any)=> <div>lsp 0 hover</div>;
export const lsp_detail_1 = (p:any)=> <div>lsp 1 goto def</div>;
export const lsp_detail_2 = (p:any)=> <div>lsp 2 references</div>;
export const lsp_detail_3 = (p:any)=> <div>lsp 3 rename</div>;
export const lsp_detail_4 = (p:any)=> <div>lsp 4 hover</div>;
export const lsp_detail_5 = (p:any)=> <div>lsp 5 goto def</div>;
export const lsp_detail_6 = (p:any)=> <div>lsp 6 references</div>;
export const lsp_detail_7 = (p:any)=> <div>lsp 7 rename</div>;
export const lsp_detail_8 = (p:any)=> <div>lsp 8 hover</div>;
export const lsp_detail_9 = (p:any)=> <div>lsp 9 goto def</div>;
export const lsp_detail_10 = (p:any)=> <div>lsp 10 references</div>;
export const lsp_detail_11 = (p:any)=> <div>lsp 11 rename</div>;
export const lsp_detail_12 = (p:any)=> <div>lsp 12 hover</div>;
export const lsp_detail_13 = (p:any)=> <div>lsp 13 goto def</div>;
export const lsp_detail_14 = (p:any)=> <div>lsp 14 references</div>;
export const lsp_detail_15 = (p:any)=> <div>lsp 15 rename</div>;
export const lsp_detail_16 = (p:any)=> <div>lsp 16 hover</div>;
export const lsp_detail_17 = (p:any)=> <div>lsp 17 goto def</div>;
export const lsp_detail_18 = (p:any)=> <div>lsp 18 references</div>;
export const lsp_detail_19 = (p:any)=> <div>lsp 19 rename</div>;